import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
// import "@uploadthing/react/styles.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div >
        <Providers>
          <body className="subHeaderFont background-color">{children}</body>
        </Providers>
      </div>
    </html>
  );
}
