import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import FooterComp from "@/components/footerComp";
import { InputWithButton } from "@/components/subscribeComp";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="subHeaderFont">
    
        {children}
    </body>
    </html>
  );
}
